<div class="product-info">

    <div class="row">
        <div class="col-xs-3">
            <a href="#" class="btn btn-default btn-sm btn-collapse-product"><i class="fa fa-fw fa-reply"></i> Back</a>
        </div>
        <div class="col-xs-2 text-right">
            <img width="64" height="64" src="assets/img/products/lims.png" data-retina-src="assets/img/products/lims@2x.png">
        </div>
        <div class="col-xs-4 product-title">
            <h4>LabScout&trade; LIMS</h4>
        </div>
        <div class="col-xs-3 text-right">
            <a href="ajax/products/consult?product=lims" class="btn btn-warning btn-lg btn-product-ajax"><i class="fa fa-question-circle"></i> Consult</a>
        </div>
    </div>
    
    <ul class="nav nav-tabs">
        <li class="active"><a href="#product-summary" data-toggle="tab"><?= H('Overview')?></a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="product-summary" style="padding:30px 40px 20px">
            <p class="text-justify">Laboratory Information Management System (here after refers to LabScout LIMS) is a
powerful web-based laboratory software system, combining several key factors of the lab together and significantly increasing the efficiency and automation of laboratory management, turning your work place into a paper-free environment. LabScout LIMS is designed for middle size bio-scientific laboratory. There is nothing to download or install. The web interface is designed to be user-friendly, safe, compatible and simple. By adopting the Software as a Service mode, LabScout LIMS offers you the unique personalized management software, providing you the functional modules that perfectly match your needs. 
</p>
            <p class="text-justify">To make your lab function at peak efficiency, this software provides you:</p>
            <ul>
            	<li>Track your inventory</li>
            	<li>Calendar schedule</li>
            	<li>Researchers management</li>
                <li>Expenditure account</li>
            </ul>
        </div>
    </div>

</div>
