<div class="product-info">

    <div class="row">
        <div class="col-xs-3">
            <a href="#" class="btn btn-default btn-sm btn-collapse-product"><i class="fa fa-fw fa-reply"></i> 返回</a>
        </div>
        <div class="col-xs-2 text-right">
            <img width="64" height="64" src="assets/img/products/giot.png" data-retina-src="assets/img/products/giot@2x.png">
        </div>
        <div class="col-xs-4 product-title">
            <h4>G-IoT</h4>
            <h3>物联网智慧科研管理体系</h3>
        </div>
        <div class="col-xs-3 text-right">
            <a href="ajax/products/consult?product=giot" class="btn btn-warning btn-lg btn-product-ajax"><i class="fa fa-question-circle"></i> 咨询</a>
        </div>
    </div>


    <ul class="nav nav-tabs">
        <li class="active"><a href="#product-summary" data-toggle="tab"><?= H(T('概述'))?></a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="product-summary" style="padding:30px 40px 20px">
            <p class="text-justify text-indent"><strong>GIoT</strong></p>
        </div>
    </div>
    
</div>
