<div class="product-info">

    <div class="row">
        <div class="col-xs-3">
            <a href="#" class="btn btn-default btn-sm btn-collapse-product"><i class="fa fa-fw fa-reply"></i> 返回</a>
        </div>
        <div class="col-xs-2 text-right">
            <img width="64" height="64" src="assets/img/products/mall.png" data-retina-src="assets/img/products/mall@2x.png">
        </div>
        <div class="col-xs-4 product-title">
            <h4>LabScout&trade; Mall</h4>
            <h3>科研采购管理系统</h3>
        </div>
        <div class="col-xs-3 text-right">
            <a href="ajax/products/consult?product=mall" class="btn btn-warning btn-lg btn-product-ajax"><i class="fa fa-question-circle"></i> 咨询</a>
        </div>
    </div>


    <ul class="nav nav-tabs">
        <li class="active"><a href="#product-summary" data-toggle="tab"><?= H(T('概述'))?></a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="product-summary" style="padding:30px 40px 20px">
            <p class="text-justify text-indent">MALL是基理科技自主研发的在线科研采购管理系统，系统全面整合商品查找、选购、付款、收货、报销结算等各个环节，通过线上平台为科研工作者提供丰富的试剂、耗材等实验室用品信息，用户随时能够以透明实惠的价格买到最合适的产品，有效节省选购时间，缩短供货周期。同时，科研采购管理系统还可以与LabScout LIMS 实验室信息管理系统中的订单管理模块进行无缝衔接，实现科研物品从申请到订购的全程数字化管理，极大提高了科研工作效率，让实验室人员能够将更多的精力投入到科研工作中。基理科技以“来源于科研，服务于科研”为宗旨，与您并肩助力科研事业发展。</p>
            <h4 class="text-center">特点：物品采购全流程电子化管理、财务结算全过程在线上完成</h4>
        </div>
    </div>
    
</div>
