<div class="page-content">
    <h2 class="page-title">成功案例</h2>
    <br>
    <h4>
        <img src="assets/img/customers/china.png" data-retina-src="assets/img/customers/china@2x.png" height="30"> China
    </h4>
    <div class="row">
        <div class="col-xs-2 text-center customer">
            <a href="http://www.nankai.edu.cn" target="_blank"><span class="customer-logo-nankai"></span></a>
            <h5>Nankai University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.tju.edu.cn" target="_blank"><span class="customer-logo-tju"></span></a>
            <h5>Tianjin University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.tsinghua.edu.cn" target="_blank"><span class="customer-logo-tsinghua"></span></a>
            <h5>Tsinghua University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.pku.edu.cn" target="_blank"><span class="customer-logo-pku"></span></a>
            <h5>Peking University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.fudan.edu.cn" target="_blank"><span class="customer-logo-fudan"></span></a>
            <h5>Fudan University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.sjtu.edu.cn" target="_blank"><span class="customer-logo-sjtu"></span></a>
            <h5>Shanghai Jiaotong University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.sdu.edu.cn" target="_blank"><span class="customer-logo-sdu"></span></a>
            <h5>Shandong University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.xjtu.edu.cn" target="_blank"><span class="customer-logo-xjtu"></span></a>
            <h5>Xi'an Jiaotong University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.bit.edu.cn" target="_blank"><span class="customer-logo-bit"></span></a>
            <h5>Beijing Institue of Technology</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.jiangnan.edu.cn" target="_blank"><span class="customer-logo-jiangnan"></span></a>
            <h5>Jiangnan University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.ybu.edu.cn" target="_blank"><span class="customer-logo-ybu"></span></a>
            <h5>Yanbin University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.hebut.edu.cn" target="_blank"><span class="customer-logo-hebut"></span></a>
            <h5>Hebei University of Technology</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.cas.cn" target="_blank"><span class="customer-logo-cas"></span></a>
            <h5>Chinese Academy of Sciences</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.caas.net.cn" target="_blank"><span class="customer-logo-caas"></span></a>
            <h5>Chinese Academy of Agricultural Sciences</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.whbio.org.cn" target="_blank"><span class="customer-logo-whbio"></span></a>
            <h5>Wuhan Institute of Biotechnology</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.medmax.cn" target="_blank"><span class="customer-logo-cmc"></span></a>
            <h5>China Medical City (Taizhou)</h5>
        </div>
        
        <div class="col-xs-2 text-center customer">
            <a href="http://www.swjtu.edu.cn" target="_blank"><span class="customer-logo-swjtu"></span></a>
            <h5>Southwest Jiaotong University</h5>
        </div>
        
        <div class="col-xs-2 text-center customer">
            <a href="http://www.tijmu.edu.cn" target="_blank"><span class="customer-logo-tijmu"></span></a>
            <h5>Tianjin Medical University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.hbu.edu.cn" target="_blank"><span class="customer-logo-hbu"></span></a>
            <h5>Hebei University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.bme.org.cn/Pages/DefaultPage.aspx" target="_blank"><span class="customer-logo-bme"></span></a>
            <h5>Chinese Academy of Medical Sciences</h5>
        </div>
        
        <div class="col-xs-2 text-center customer">
            <a href="http://www.cug.edu.cn/new" target="_blank"><span class="customer-logo-cug"></span></a>
            <h5 class="customer-title-cug">China University of Geosciences (Wuhan)</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.henannu.edu.cn" target="_blank"><span class="customer-logo-henannu"></span></a>
            <h5>Henan Normal University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.hunau.net" target="_blank"><span class="customer-logo-hunau"></span></a>
            <h5>Hunan Agricultural University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.hunnu.edu.cn" target="_blank"><span class="customer-logo-hunnu"></span></a>
            <h5>Hunan Normal University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.neau.edu.cn/" target="_blank"><span class="customer-logo-neau"></span></a>
            <h5>Northeast Agricultural University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.seu.edu.cn/" target="_blank"><span class="customer-logo-seu"></span></a>
            <h5>Southeast University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.cau.edu.cn" target="_blank"><span class="customer-logo-cau"></span></a>
            <h5>China Agricultural University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.xmu.edu.cn" target="_blank"><span class="customer-logo-xmu"></span></a>
            <h5>Xiamen University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.njtech.edu.cn" target="_blank"><span class="customer-logo-njtech"></span></a>
            <h5>Nanjing Tech University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.cnu.edu.cn" target="_blank"><span class="customer-logo-cnu"></span></a>
            <h5>Capital Normal University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.bnu.edu.cn" target="_blank"><span class="customer-logo-bnu"></span></a>
            <h5>Beijing Normal University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.xjmu.edu.cn" target="_blank"><span class="customer-logo-xjmu"></span></a>
            <h5>Xinjiang Medical University</h5>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.ouc.edu.cn" target="_blank"><span class="customer-logo-ouc"></span></a>
            <h5>Ocean University of China</h5>
        </div>









    </div>
    <br>
    <h4>
        <img src="assets/img/customers/misc.png" data-retina-src="assets/img/customers/misc@2x.png" height="30"> Overseas
    </h4>
    <div class="row">
        <div class="col-xs-2 text-center customer">
            <a href="http://www.harvard.edu" target="_blank"><span class="customer-logo-harvard"></span></a>
            <h5>Harvard University</h5>
            <h6 class="text-muted">US</h6>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.rutgers.edu" target="_blank"><span class="customer-logo-rutgers"></span></a>
            <h5>Rutgers University</h5>
            <h6 class="text-muted">US</h6>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.ntu.edu.sg" target="_blank"><span class="customer-logo-ntu"></span></a>
            <h5>Nanyang Technological University</h5>
            <h6 class="text-muted">Singapore</h6>
        </div>
        <div class="col-xs-2 text-center customer">
            <a href="http://www.m2p-labs.com" target="_blank"><span class="customer-logo-m2p"></span></a>
            <h5>m2p-Labs GmbH</h5>
            <h6 class="text-muted">Germany</h6>
        </div>
    </div>

</div>
