<div class="page-content">
    <h2 class="page-title">Product &amp; Service</h2>

    <div class="products clearfix" >
        <div class="product" data-name="lims">
            <div class="product-icon">
                <img src="assets/img/products/lims.png" data-retina-src="assets/img/products/lims@2x.png">
            </div>
            <div class="product-content">
                <p class="text-justify" style="margin-top:.5em"><strong>LIMS</strong> 以实验室为中心，结合应用软件与互联网技术，根据科研人员的工作需要，将多个影响实验室运作的必要因素有机地结合起来，从而大幅度提高实验室管理效率和自动化水平，为您的实验室实现简易便捷的无纸化管理环境。</p>
            </div>
        </div>
        <div class="product" data-name="lims-cf">
            <div class="product-icon">
                <img src="assets/img/products/cf.png" data-retina-src="assets/img/products/cf@2x.png">
            </div>
            <div class="product-content">
                <p class="text-justify" style="margin-top:.5em"> <strong>LIMS-CF</strong> 是一款专门面向科研实验室公共仪器的智能化管理系统。本系统将公共仪器平台的各项必要工作流程整合在一起，显著提高仪器设备的管理和使用效率。</p>
            </div>
        </div>
        <div class="product" data-name="labmai">
            <div class="product-icon">
                <img src="assets/img/products/mall.png" data-retina-src="assets/img/products/mall@2x.png">
            </div>
            <div class="product-content">
                <p class="text-justify" style="margin-top:.5em"> <strong>LabMai</strong> 是基理科技自主研发的在线科研采购管理系统，系统全面整合产品查找、选购、付款、收货、报销结算等各个环节，通过线上平台为科研工作者提供丰富的试剂、耗材等实验室用品信息，用户随时能够以透明实惠的价格买到最合适的产品，有效节省选购时间，缩短供货周期。</p>
            </div>
        </div>
        <div class="product" data-name="giot">
            <div class="product-icon">
            </div>
            <div class="product-content">
                <p class="text-justify" style="margin-top:.5em"> <strong>G-IoT</strong> 是一个物联网智能科研管理体系，通过多种接入云端的智能硬件终端，将科研实验室的环境、能耗、数据、仪器控制有机的结合在一起。</p>
            </div>
        </div>
        <div class="product-expanded"></div>
    </div>

    <div class="product-indicator-track">
        <div class="product-indicator"></div>
    </div>

    <div class="product-tabs clearfix">
        <div class="product-tab">
            <h4>LIMS</h4>
            <h5>实验室信息管理系统</h5>
        </div>
        <div class="product-divider"></div>
        <div class="product-tab">
            <h4>LIMS-CF</h4>
            <h5>仪器共享管理系统</h5>
        </div>
        <div class="product-divider"></div>
        <div class="product-tab">
            <h4>LabMai</h4>
            <h5>科研采购管理系统</h5>
        </div>
        <div class="product-divider"></div>
        <div class="product-tab">
            <h4>G-IoT</h4>
            <h5>物联智慧科研</h5>
        </div>
    </div>

</div>
<script data-ajax="true">
require(['main'], function($) {
    
    var $indicator = $('#page-products .product-indicator');    
    var $products = $('#page-products .products');
    var $expanded_product = $products.children('.product-expanded');
    
    $products.children('.product').hover(function(){
        if ($expanded_product.is(':visible')) return;

        var $product = $(this);
        $indicator.css({left: $product.position().left + $product.width() / 2});
        $product.addClass('hover').siblings().removeClass('hover');
    })
    .on('click.expand-product', function() {
        var $product = $(this);
        _expand_product($product);
    });
    
    $products.children('.product').eq(0).trigger('mouseover');
    
    var $loading = $('<div class="text-center text-muted" style="padding-top:100px"><i class="fa fa-4x fa-spinner fa-spin"></i></div>');

    function _expand_product($product) {
        
        var $collapsed_product = $expanded_product.data('product');
        if ($collapsed_product) {
            
            if ($collapsed_product[0] == $product[0]) return;
            
            // 重新显示indicator
            $indicator.css({left: $collapsed_product.position().left + $collapsed_product.width() / 2});
            $collapsed_product.addClass('hover').siblings().removeClass('hover');
        
            $expanded_product.data('product', null);
            $expanded_product.empty().fadeOut();
        }

        // 重新显示indicator
        $indicator.css({left: $product.position().left + $product.width() / 2});
        $product.addClass('hover').siblings().removeClass('hover');

        $expanded_product.append($loading);
        $expanded_product.data('product', $product);
        
        $expanded_product.fadeIn(function(){
            $expanded_product.load('ajax/products/view/' + $product.data('name'));
        });
    }
    
    $('#page-products .product-tab')
    .hover(function() {
        if ($expanded_product.is(':visible')) return;
        
        var index = $('#page-products .product-tab').index(this);
        var $product = $products.children('.product').eq(index);
        $indicator.css({left: $product.position().left + $product.width() / 2});
        $product.addClass('hover').siblings().removeClass('hover');
    })
    .on('click.expand-product', function(){
        var index = $('#page-products .product-tab').index(this);
        var $product = $products.children('.product').eq(index);
        _expand_product($product);
    });
    
    $('#page-products').on('click', 'a.btn-collapse-product', function(){
        var $expanded_product = $(this).parents('.product-expanded');
        $expanded_product.data('product', null);
        $expanded_product.empty().fadeOut();
        return false;
    });
    
    $('#page-products').on('click', 'a.btn-product-ajax', function(e){
        var $a = $(this);
        $expanded_product.empty().append($loading).fadeIn(function(){
            $expanded_product.load($a.attr('href'));
        });
        return false;
    });

});
</script>