<div class="page-content">
    <h2 class="page-title"><?= H('Product & Service')?></h2>

    <div class="products clearfix" >
        <div class="product" data-name="17kong">
            <div class="product-icon">
                <img src="assets/img/products/17kong.png" data-retina-src="assets/img/products/17kong@2x.png">
            </div>
            <div class="product-content">
                <p style="margin-top:.5em"><strong>17Kong</strong> originally called LabScout LIMS-CF, allows easy management to laboratory equipment and apparatus on a cloud platform, increasing the efficiency of the usage of large-scale instruments</p>
            </div>
        </div>
        <div class="product" data-name="lims">
            <div class="product-icon">
                <img src="assets/img/products/lims.png" data-retina-src="assets/img/products/lims@2x.png">
            </div>
            <div class="product-content">
                <p style="margin-top:.5em"><strong>LabScout LIMS</strong> is a powerful web-based laboratory software system, combining several key factors of the lab together and significantly increasing the efficiency and automation of laboratory management, turning your work place into a paper-free environment.</p>
            </div>
        </div>
        <div class="product" data-name="labmai">
            <div class="product-icon">
                <img src="assets/img/products/labmai.png" data-retina-src="assets/img/products/labmai@2x.png">
            </div>
            <div class="product-content">
                <p style="margin-top:.5em"> <strong>LabMai</strong> is a cloud platform that manages laboratory purchase. This system integrates the whole process of purchase, including product search, selection, payment, delivery, reimbursement and settlement. It provides diverse options of reagent and other lab supplies. Customers can always use the most reasonable price to buy their fit products, and it also saves times in this purchase cycle. </p>
            </div>
        </div>
        <div class="product" data-name="giot">
            <div class="product-icon">
                <img src="assets/img/products/giot.png" data-retina-src="assets/img/products/giot@2x.png">
            </div>
            <div class="product-content">
                <p style="margin-top:.5em"> <strong>G-IoT</strong> based on Internet-of-Things, G-IoT is a system that is able to intelligently manage scientific research. By accessing the cloud data on hardware terminals, this system is able to integrate lab environment, energy consumption, data and equipment control all together. </p>
            </div>
        </div>
        <div class="product-expanded"></div>
    </div>

</div>
<script data-ajax="true">
require(['main'], function($) {
    
    var $products = $('#page-products .products');
    var $expanded_product = $products.children('.product-expanded');
    
    $products.children('.product').hover(function(){
        if ($expanded_product.is(':visible')) return;

        var $product = $(this);
        $product.addClass('hover').siblings().removeClass('hover');
    })
    .on('click.expand-product', function() {
        var $product = $(this);
        _expand_product($product);
    });
    
    $products.children('.product').eq(0).trigger('mouseover');
    
    var $loading = $('<div class="text-center text-muted" style="padding-top:100px"><i class="fa fa-4x fa-spinner fa-spin"></i></div>');

    function _expand_product($product) {
        
        var $collapsed_product = $expanded_product.data('product');
        if ($collapsed_product) {
            
            if ($collapsed_product[0] == $product[0]) return;
            
            $collapsed_product.addClass('hover').siblings().removeClass('hover');
        
            $expanded_product.data('product', null);
            $expanded_product.empty().fadeOut();
        }

        $product.addClass('hover').siblings().removeClass('hover');

        $expanded_product.append($loading);
        $expanded_product.data('product', $product);
        
        $expanded_product.fadeIn(function(){
            $expanded_product.load('ajax/products/view/' + $product.data('name'));
        });
    }
    
    $('#page-products').on('click', 'a.btn-collapse-product', function(){
        var $expanded_product = $(this).parents('.product-expanded');
        $expanded_product.data('product', null);
        $expanded_product.empty().fadeOut();
        return false;
    });
    
    $('#page-products').on('click', 'a.btn-product-ajax', function(e){
        var $a = $(this);
        $expanded_product.empty().append($loading).fadeIn(function(){
            $expanded_product.load($a.attr('href'));
        });
        return false;
    });

});
</script>