<div class="product-info">

    <div class="row">
        <div class="col-xs-3">
            <a href="#" class="btn btn-default btn-sm btn-collapse-product"><i class="fa fa-fw fa-reply"></i> 返回</a>
        </div>
        <div class="col-xs-2 text-right">
            <img width="64" height="64" src="assets/img/products/tender.png" data-retina-src="assets/img/products/tender@2x.png">
        </div>
        <div class="col-xs-4 product-title">
            <h4>LabScout&trade; Tender</h4>
            <h3>采购竞价系统</h3>
        </div>
        <div class="col-xs-3 text-right">
            <a href="ajax/products/consult?product=tender" class="btn btn-warning btn-lg btn-product-ajax"><i class="fa fa-question-circle"></i> 咨询</a>
        </div>
    </div>

    <ul class="nav nav-tabs">
        <li class="active"><a href="#product-summary" data-toggle="tab"><?= H(T('概述'))?></a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="product-summary" style="padding:30px 40px 20px">
            <p class="text-justify text-indent">网上竞价系统是基理科技结合高校采购流程，通过优化再造所研发的一款电子采购平台。通过信息发布，商家报价，网上定标及结果公布等流程实现全透明监管，有效防止物品采购过程中的暗箱操作。采用该系统可进一步规范商品交易的竞价行为，充分体现公平、公开、公正的原则，它的投入运行必将提高高校固定资产购置的管理水平和效率。
</p>
            <h4 class="text-center">特点：自主发布采购需求、多商家参与竞价、用户自主选择、管理部门审核确认、与高校财务进行对接</h4>
        </div>
    </div>

</div>
