<div class="culture-content">
    <h4><strong>Professionalism</strong> is the guarantee of quality</h4>
    <h4><strong>Innovations</strong> is the source of competition</h4>
    <h4><strong>High efficiency</strong> is our working attitude</h4>
    <h4><strong>Detail</strong> is the premise of making good products</h4>
    <h4><strong>Honesty</strong> makes us successful in the market</h4>
    <h4><strong>Service-oriented</strong> is what we are based on</h4>
</div>