<div class="honors-content">
    <div class="honors-title">
        <div class="left-flag"></div>
        <div class="right-flag"></div>
        <div class="content"><?= H(T('企业荣誉'))?></div>
        <div class="left-shadow"></div>
        <div class="right-shadow"></div>
    </div>
    <div class="honors-body">
        <ol>
            <li>多项软件著作权和专利；</li>
            <li>通过多项企业资质认定；</li>
            <li>承担多项国家资助在研项目5项；</li>
            <li>通过多项产品资质认定；</li>
            <li>海内外媒体报道；</li>
            <li>团队人员通过千人计划和海外高层次评定；</li>
        </ol>
    </div>
</div>