<div class="honors-content">
    <div class="honors-title">
        <div class="left-flag"></div>
        <div class="right-flag"></div>
        <div class="content">Enterprise Honor</div>
        <div class="left-shadow"></div>
        <div class="right-shadow"></div>
    </div>
    <div class="honors-body">
        <ol>
            <li>Multiple software copyright and patents；</li>
            <li>Been through several enterprise qualifications；</li>
            <li>Undertake five State funded research projects；</li>
            <li>Been through several product qualifications；</li>
            <li>National and overseas press release；</li>
            <li>团队人员通过千人计划和海外高层次评定；</li>
        </ol>
    </div>
</div>