<div class="team-content">
    <?php
    $members = [
        'qian' => [
            'href' => '#qian',
            'title' => 'Qian Wang',
        ],
        'jia' => [
            'href' => '#jia',
            'title' => 'Jia Huang',
        ],
        'pc' => [
            'href' => '#qiu',
            'title' => 'Zhigang Chen',
        ],
    ];
    ?>
    <div class="members-canvas">
        <div class="members">
            <div class="member" data-member="qian">
                <div class="container">
                    <div class="row" style="margin-bottom:10px">
                        <div class="col-xs-5 text-right" style="padding-right:0">
                            <img class="portrait" src="assets/img/about/team/qian.png" data-retina-src="assets/img/about/team/qian@2x.png">
                        </div>
                        <div class="col-xs-6" style="padding-left:0">
                            <div class="text-center" style="float:left">
                                <h4 class="name">Qian Wang</h4>
                                <h5 class="title">CEO / Co-Founder</h5>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <p class="text-justify text-indent">Ph.D. at New York University, active in life science field and the American exchange student community. Was once vice president at CHI Scientific Inc. in 2007, responsible for product development and marketing. Was principle at many overseas workstations, and was also senior consultant at many domestic biomedical companies and government sectors. She successfully built a strategic cooperative platform between Chinese and American biomedical and medical equipment companies.</p>
                    </div>
                </div>
            </div>
            <div class="member" data-member="jia">
                <div class="container">
                    <div class="row" style="margin-bottom:10px">
                        <div class="col-xs-5 text-right" style="padding-right:0">
                            <img class="portrait" src="assets/img/about/team/jia.png" data-retina-src="assets/img/about/team/jia@2x.png">
                        </div>
                        <div class="col-xs-6" style="padding-left:0">
                            <div class="text-center" style="float:left">
                                <h4 class="name">黄嘉</h4>
                                <h5 class="title">CTO / 联合创始人</h5>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <p class="text-justify text-indent">复旦大学博士。具有多年软硬件研发和网络开发经验，长期致力于推动生物医学领域的信息网络化发展。曾主持过多个国内外生物医药相关企业及科研机构的在线软件平台的搭建，并参与过凝胶成像/医疗仪器信号采集分析等多种生物科研软硬接口软件项目的开发工作。</p>
                    </div>
                </div>
            </div>
            <div class="member" data-member="qiu">
                <div class="container">
                    <div class="row" style="margin-bottom:10px">
                        <div class="col-xs-5 text-right" style="padding-right:0">
                            <img class="portrait" src="assets/img/about/team/qiu.png" data-retina-src="assets/img/about/team/qiu@2x.png">
                        </div>
                        <div class="col-xs-6" style="padding-left:0">
                            <div class="text-center" style="float:left">
                                <h4 class="name">陈志刚</h4>
                                <h5 class="title">COO</h5>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <p class="text-justify text-indent">从事互联网及生物医药领域信息化管理工作十余年，积累了丰富的互联网产品研发、项目规划管理、产品运营和电子商务营销推广等方面经验。是国内较早的生物门户网站“生物通”的创办人之一。在北京东胜创新生物科技有限公司工作期间，组建电子商务部并担任部门总经理，组建全国分销渠道并从事销售管理工作，电商销售业绩优秀。</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="member-navbar clearfix">
        <?php foreach($members as $key => $item) { ?>
            <div class="member-navbar-item">
                <a href="<?= H($item['href']) ?>">
                    <?= H($item['title']) ?>
                </a>
            </div>
        <?php } ?>        
    </div>
    <script>
    require(['main'], function($){
        $('#page-about .about-card-team .member-navbar-item a')
        .on('click', function(){
            var $a = $(this);
            var $item = $a.parents('.member-navbar-item');
            $item.addClass('hover').siblings().removeClass('hover');
    
            var href = $a.attr('href').substr(1);
            var $member = $('#page-about .about-card-team .member[data-member="'+href+'"]');
            $('#page-about .about-card-team .members').animate({left:-$member.position().left});
    
            return false;
        })
        .eq(0).click();
    })

    </script>
</div>