<div class="us-content">
    <p class="text-indent text-justify">
    天津市基理科技有限公司成立于2008年，研发总部设立在北方经济中心天津， 于美国波士顿成立分部。公司创始人均为科研和IT领域的留学归国博士，在软硬件自主研发与营销管理等方面拥有深厚的背景和经验。公司通过为全球多个国家和地区的高校和科研实验室用户提供创新技术与解决方案，让全世界用户享受简单便捷的科研管理环境。
    </p>
    <p>我们的愿景: </p>
    <p class="text-indent text-justify">
    <big><strong>“成为国际领先的科研管理智能化产品提供商”</strong></big>
    </p>
    <p>我们的使命: </p>
    <p class="text-indent text-justify">
    <big><strong>“让科研变得更简单”</strong></big>
    </p>
</div>