<div class="us-content">
    <p class="text-indent text-justify">
    Tianjin Genee Group LLC was founded in 2008, headquarters set in Tianjin, the economic center of northern China, with a branch office in Boston, America. Our two founders, both doctors in science and Internet fields, both have deep experience in research and development in software and hardware, and management in marketing. We provide lab users around the world with our ideas and products, allowing them to enjoy the most simple and convenient laboratory environment.
    </p>
    <p>Our desire: </p>
    <p class="text-indent text-justify">
    <big><strong>“Becoming a leading international provider of lab management smart products.”</strong></big>
    </p>
    <p>Our mission: </p>
    <p class="text-indent text-justify">
    <big><strong>“Research gets easier”</strong></big>
    </p>
</div>