<div class="product-info">

    <div class="row">
        <div class="col-xs-3">
            <a href="#" class="btn btn-default btn-sm btn-collapse-product"><i class="fa fa-fw fa-reply"></i> 返回</a>
        </div>
        <div class="col-xs-2 text-right">
            <img width="64" height="64" src="assets/img/products/billing.png" data-retina-src="assets/img/products/billing@2x.png">
        </div>
        <div class="col-xs-4 product-title">
            <h4>LabScout&trade; Billing</h4>
            <h3>实验室快捷支付系统</h3>
        </div>
        <div class="col-xs-3 text-right">
            <a href="ajax/products/consult?product=billing" class="btn btn-warning btn-lg btn-product-ajax"><i class="fa fa-question-circle"></i> 咨询</a>
        </div>
    </div>


    <ul class="nav nav-tabs">
        <li class="active"><a href="#product-summary" data-toggle="tab"><?= H(T('概述'))?></a></li>
        <li><a href="#product-feature" data-toggle="tab"><?= H(T('产品功能'))?></a></li>
        <li><a href="#product-advantage" data-toggle="tab"><?= H(T('产品优势'))?></a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="product-summary" style="padding:30px 40px 20px">
            <p class="text-indent text-justify">LabScout&trade; Billing是基理科技推出的一款独立支付结算平台，可以与多个充值支付系统进行对接，为用户提供更加灵活的充值分配结算的解决方案。同时，该平台还可以与LabScout&trade; LIMS-CF大型仪器共享管理系统进行充值绑定，让科研用户的经费能够在各个系统中方便自如的分配。</p>
        </div>
        <div class="tab-pane" id="product-feature" style="padding:30px 40px 20px">
            <p class="text-indent text-justify">对接多个支付系统、用户自助进行财务转账、随时查看支付明细</p>
        </div>
        <div class="tab-pane" id="product-advantage" style="padding:30px 40px 20px">
            <ul style="list-style:none;padding:0">
                <li><i class="fa fa-check fa-fw"></i> 集中自如地调整您的经费</li>
                <li><i class="fa fa-check fa-fw"></i> 可与高校财务系统进行对接</li>
                <li><i class="fa fa-check fa-fw"></i> 方便快捷的自主充值</li>
                <li><i class="fa fa-check fa-fw"></i> 实验经费灵活自由分配</li>
            </ul>
        </div>
    </div>
    
</div>
