<div class="product-info">

    <div class="row">
        <div class="col-xs-3">
            <a href="#" class="btn btn-default btn-sm btn-collapse-product"><i class="fa fa-fw fa-reply"></i> 返回</a>
        </div>
        <div class="col-xs-2 text-right">
            <img width="64" height="64" src="assets/img/products/cf.png" data-retina-src="assets/img/products/cf@2x.png">
        </div>
        <div class="col-xs-4 product-title">
            <h4>LabScout&trade; LIMS-CF</h4>
            <h3>公共仪器共享管理系统</h3>
        </div>
        <div class="col-xs-3 text-right">
            <a href="ajax/products/consult?product=lims-cf" class="btn btn-warning btn-lg btn-product-ajax"><i class="fa fa-question-circle"></i> 咨询</a>
        </div>
    </div>
    
    <ul class="nav nav-tabs">
        <li class="active"><a href="#product-summary" data-toggle="tab"><?= H(T('概述'))?></a></li>
        <li><a href="#product-feature" data-toggle="tab"><?= H(T('产品功能'))?></a></li>
        <li><a href="#product-advantage" data-toggle="tab"><?= H(T('产品优势'))?></a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="product-summary" style="padding:30px 40px 20px">
            <p class="text-justify text-indent">LabScout LIMS-CF（Laboratory Information Management System-Core Facility） 仪器协作共享管理系统是一款专门面向科研实验室公共仪器的智能化管理系统。本系统将公共仪器平台的各项必要工作流程整合在一起，显著提高仪器设备的管理和使用效率。</p>	
            <ul>
                <li>信息共享    资源不浪费</li>
                <li>预约授权    使用不等候</li>
                <li>实时监控    状态全知道</li>        
                <li>远程协助    问题不拖延</li>      
                <li>计费结算    收费更轻松</li>
                <li>仪器绩效    统计不头痛</li>
            </ul>
        </div>
        <div class="tab-pane" id="product-feature" style="padding:30px 40px 20px">
            <div style="overflow:hidden;width:850px;height:220px;position:relative;margin:0 auto">
                <div id="product-feature-canvas">
                    <div class="row">
                        <div class="col-xs-4">
                            <div class="form-group clearfix">
                                <i class="text-primary fa fa-fw fa-3x fa-info-circle pull-left"></i>
                                <h5 style="margin-left:42px; margin-top:0">专业的仪器展示与共享</h5>
                                <ul class="text-muted" style="margin-left:42px; font-size:85%">
                                    <li>前后台数据同步更新</li>
                                    <li>通知公告实时发布</li>
                                    <li>仪器资源便捷导航</li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-xs-4">
                            <div class="form-group clearfix">
                                <i class="text-primary fa fa-fw fa-3x fa-users pull-left"></i>
                                <h5 style="margin-left:42px; margin-top:0">灵活的人员权限</h5>
                                <ul class="text-muted" style="margin-left:42px; font-size:85%">
                                    <li>角色权限灵活设定</li>
                                    <li>多级分权系统管理</li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-xs-4">
                            <div class="form-group clearfix">
                                <i class="text-primary fa fa-fw fa-3x fa-calendar pull-left"></i>
                                <h5 style="margin-left:42px; margin-top:0">仪器在线预约与授权使用</h5>
                                <ul class="text-muted" style="margin-left:42px; font-size:85%">
                                    <li>直观明了的预约界面</li>
                                    <li>方式多样的用户鉴权</li>
                                    <li>清晰规范的使用记录</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-4">
                            <div class="form-group clearfix">
                                <i class="text-primary fa fa-fw fa-3x fa-cogs pull-left"></i>
                                <h5 style="margin-left:42px; margin-top:0">自动化财务计费与结算</h5>
                                <ul class="text-muted" style="margin-left:42px; font-size:85%">
                                    <li>收费方式多样化</li>
                                    <li>计费结算智能化</li>
                                    <li>统计数据准确化</li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-xs-4">
                            <div class="form-group clearfix">
                                <i class="text-primary fa fa-fw fa-3x fa-bar-chart-o pull-left"></i>
                                <h5 style="margin-left:42px; margin-top:0">便捷的报表统计和绩效考核</h5>
                                <ul class="text-muted" style="margin-left:42px; font-size:85%">
                                    <li>仪器运行数据自动采集</li>
                                    <li>绩效统计报表一键导出</li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-xs-4">
                            <div class="form-group clearfix">
                                <i class="text-primary fa fa-fw fa-3x fa-puzzle-piece pull-left"></i>
                                <h5 style="margin-left:42px; margin-top:0">高效扩展功能</h5>
                                <ul class="text-muted" style="margin-left:42px; font-size:85%">
                                    <li>可定制模块化设计</li>
                                    <li>软硬件结合的全方位管理</li>
                                    <li>新功能模块持续不断推出</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
       </div>
        <div class="tab-pane" id="product-advantage" style="padding:30px 40px 20px">
            <ul style="list-style:none;padding:0">
                <li><i class="fa fa-check fa-fw"></i> 模块搭配灵活，权限设置合理，满足多种管理需求。</li>
                <li><i class="fa fa-check fa-fw"></i> 支持统一身份验证，兼容校园一卡通，能够与其他系统实现单点登录。</li>
                <li><i class="fa fa-check fa-fw"></i> 预留标准化接口，从结构上保证系统极佳的扩展性和灵活性，轻松实现新仪器设备的后续整合及软件功能的升级更新。</li>
                <li><i class="fa fa-check fa-fw"></i> 兼容性强， 仪器授权客户端支持Windows/Mac等操作系统，满足科研用户的专业需求。</li>
                <li><i class="fa fa-check fa-fw"></i> 系统支持多语种，满足科研单位的国际化合作需求。</li>
                <li><i class="fa fa-check fa-fw"></i> 运用先进的物联网概念，支持扩展多种软硬件终端，仪器设备无需改装，不仅保护了仪器，也极大节约了运行成本和建设周期。</li>
            </ul>
        </div>
    </div>
    
</div>
