<!DOCTYPE html>
<html>
    <head>
    <meta charset="utf-8">
    <title><?= H(T('天津市基理科技有限公司')) ?></title>
    <base href="<?= URL('/') ?>">
    <style>
    html,body
    {
      height: 100%;
      margin: 0;
      padding: 0;
    }
    body {
        background:#f4f5f7 url('assets/img/bad-browser.png') bottom center no-repeat;
        min-height: 600px;
    }
    </style>
</head>
<body>
    
</body>
</html>