<div id="pages">
    <div id="page-home" data-anchor="home" class="page">
        <?= V('page/home') ?>
    </div>
    <div id="page-about" data-anchor="about" class="page">
        <?= V('page/about') ?>
    </div>
    <div id="page-products" data-anchor="products" class="page">
        <?= V('page/products') ?>
    </div>
    <div id="page-customers" data-anchor="customers" class="page">
        <?= V('page/customers') ?>
    </div>
</div>